# Generated by Django 3.2.8 on 2021-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(blank=True),
        ),
    ]
