# Generated by Django 3.2.8 on 2021-12-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211211_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('update_avatar', 'Can change only own avatar')]},
        ),
    ]
