# Generated by Django 3.2.8 on 2021-12-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
