# Generated by Django 3.2.4 on 2022-01-15 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220115_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_app_user_following_+', through='app.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
