# Generated by Django 3.2.4 on 2022-02-05 09:12

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220126_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=app.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
