# Generated by Django 3.2.4 on 2022-02-07 13:05

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=app.models.CloudinaryField(default='image/upload/v1644059525/media/empty_user_avatar', max_length=255, verbose_name='image'),
        ),
    ]
