# Generated by Django 3.2.4 on 2022-02-08 15:58

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=app.models.CloudinaryPostField(max_length=255, verbose_name='image'),
        ),
    ]
