# Generated by Django 3.2.8 on 2022-02-11 07:45

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=app.models.CloudinaryAvatarField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
