# Generated by Django 3.2.8 on 2022-02-11 07:48

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=app.models.CloudinaryAvatarField(default='image/upload/v1644563716/media/empty_user_avatar', max_length=255, verbose_name='image'),
        ),
    ]
